; generated by QIDIStudio
G28
M140 S100
M104 S270
; TYPE:OUTER_WALL
M104 S280 ; refiner: M2 first layer: maximum adhesion
M107 ; refiner: M2 first layer: maximum adhesion
M204 P500 ; refiner: M2 first layer: maximum adhesion
G1 X10.0 Y10.0 E1.0 F600
G1 X20.0 Y10.0 E2.0 F600
; LAYER_CHANGE
; TYPE:SPARSE_INFILL
G1 X10.0 Y10.0 E3.0 F600
; TYPE:BRIDGE
G1 X10.0 Y20.0 E4.0 F600
